server:
  port: 8099
spring:
  application:
    name: example
swagger2:
  title: swagger2测试
  description: swagger2测试描述
  exclude-path: /error, /ops/**
  contact:
    name: kevin chen
    url: kevin86.com
    email: chenkevin1986@126.com
  keyname: Authorization
  group-docket:
      aaa:
          title: group-a
          description: Starter for swagger 2.x
          version: 1.3.0.RELEASE
          termsOfServiceUrl: https://gitee.com/didispace/spring-boot-starter-swagger
          contact:
             name: zhaiyongchao
             url: http://spring4all.com/
             email: didi@potatomato.club
          excludePath: /error
      bbb:
          title: group-bbb
          excludePath: /error